import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

type ServerEntryOptions = {
  adminPrefix: string
  apiPrefix: string
}

export async function generateServerEntries(
  options: ServerEntryOptions,
  targetDir: string,
): Promise<void> {
  await Promise.all([
    writeFile(join(targetDir, 'server.ts'), serverEntry(options), 'utf8'),
    writeFile(join(targetDir, 'handler.ts'), lambdaEntry(options), 'utf8'),
    writeFile(join(targetDir, 'vercel.ts'), vercelEntry(options), 'utf8'),
  ])
}

// ─── Shared preamble ──────────────────────────────────────────────────────────

export function appSetup(): string {
  return `import config from '../../manguito.config.js'
import { schemaRegistry } from './schema-registry.js'
import { programmaticResolvers } from './programmatic-registry.js'
import { createCmsApp } from '@bobbykim/manguito-cms-api'
import { createPostgresAdapter } from '@bobbykim/manguito-cms-db'

const dbAdapter = createPostgresAdapter()
await dbAdapter.connect()

const { app } = createCmsApp({
  name: config.name,
  registry: schemaRegistry,
  db: dbAdapter.getDb(),
  storage: config.storage,
  prefix: config.api.prefix,
  resolvers: programmaticResolvers,
  ...(config.api.media ? { media: config.api.media } : {}),
  ...(config.api.rateLimit ? { rateLimit: config.api.rateLimit } : {}),
  ...(config.server.cors ? { cors: config.server.cors } : {}),
})`
}

// ─── Node HTTP server ─────────────────────────────────────────────────────────

export function serverEntry({ adminPrefix, apiPrefix }: ServerEntryOptions): string {
  return `// Generated by manguito build — do not edit manually
import { createServer } from 'node:http'
import { resolve, extname } from 'node:path'
import { readFile, stat } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { resolveStaticFile, SAFE_INLINE_MIME, ADMIN_MIME } from '@bobbykim/manguito-cms-api/runtime'
${appSetup()}

const __dist = fileURLToPath(new URL('.', import.meta.url))
const adminDir = resolve(__dist, 'admin')
const uploadsDir = resolve(__dist, '..', 'uploads')

const API_PREFIX = ${JSON.stringify(apiPrefix)}
const ADMIN_PREFIX = ${JSON.stringify(adminPrefix)}

const port = Number(process.env['PORT'] ?? 3000)

createServer(async (req, res) => {
  const url = req.url ?? '/'
  const path = url.split('?')[0] ?? '/'

  // ── API (Hono) ──────────────────────────────────────────────────────────────
  if (path.startsWith(API_PREFIX) || path.startsWith('/admin/api')) {
    const headers = new Headers()
    for (const [k, v] of Object.entries(req.headers)) {
      if (typeof v === 'string') headers.set(k, v)
      else if (Array.isArray(v)) v.forEach((vi) => headers.append(k, vi))
    }
    const body = req.method === 'GET' || req.method === 'HEAD' ? undefined : req
    const honoReq = new Request(\`http://localhost:\${port}\${url}\`, {
      method: req.method,
      headers,
      // @ts-expect-error -- Node 22 supports body as readable stream with duplex
      body,
      ...(body ? { duplex: 'half' } : {}),
    })
    const honoRes = await app.fetch(honoReq)
    res.statusCode = honoRes.status
    const setCookies: string[] = []
    honoRes.headers.forEach((v, k) => {
      if (k.toLowerCase() === 'set-cookie') setCookies.push(v)
      else res.setHeader(k, v)
    })
    if (setCookies.length > 0) res.setHeader('set-cookie', setCookies)
    res.end(Buffer.from(await honoRes.arrayBuffer()))
    return
  }

  // ── Uploads (local storage) — untrusted user content, served safely ─────────
  if (path.startsWith('/uploads/')) {
    const filePath = resolveStaticFile(uploadsDir, path.slice('/uploads'.length))
    if (!filePath) { res.statusCode = 403; res.end('Forbidden'); return }
    try {
      const data = await readFile(filePath)
      const ext = extname(filePath).slice(1).toLowerCase()
      const inline = SAFE_INLINE_MIME[ext]
      res.setHeader('X-Content-Type-Options', 'nosniff')
      if (inline) {
        res.setHeader('Content-Type', inline)
      } else {
        // Non-allowlisted extension (e.g. .html, .svg): never render inline.
        res.setHeader('Content-Type', 'application/octet-stream')
        res.setHeader('Content-Disposition', 'attachment')
      }
      res.end(data)
    } catch { res.statusCode = 404; res.end('Not found') }
    return
  }

  // ── Admin SPA ────────────────────────────────────────────────────────────────
  if (path.startsWith(ADMIN_PREFIX)) {
    const resolved = resolveStaticFile(adminDir, path.slice(ADMIN_PREFIX.length) || '/')
    let filePath = resolved ?? resolve(adminDir, 'index.html')
    try {
      const s = await stat(filePath)
      if (!s.isFile()) filePath = resolve(adminDir, 'index.html')
    } catch {
      filePath = resolve(adminDir, 'index.html')
    }
    try {
      const data = await readFile(filePath)
      // Hashed assets are content-addressed → cache forever. The SPA shell must
      // revalidate so a new deploy's index.html (referencing new asset hashes)
      // is picked up instead of a stale cached shell.
      const isAsset = path.startsWith(ADMIN_PREFIX + '/assets/')
      res.setHeader('Cache-Control', isAsset ? 'public, max-age=31536000, immutable' : 'no-cache')
      res.setHeader('Content-Type', ADMIN_MIME[extname(filePath).slice(1).toLowerCase()] ?? 'application/octet-stream')
      res.end(data)
    } catch { res.statusCode = 404; res.end('Not found') }
    return
  }

  res.statusCode = 404
  res.end('Not found')
}).listen(port, () => {
  console.log(\`Server listening on http://localhost:\${port}\`)
})
`
}

// ─── Admin SPA static serving (shared by Lambda + Vercel) ─────────────────────
//
// The Node http server (serverEntry, above) serves the built admin SPA via
// its own raw-http static file handling, entirely outside the Hono `app`.
// Lambda and Vercel only ever call handle(app), so without this they have no
// route for the admin SPA at all — only /api/* and /admin/api/* exist on
// `app` — and any request to /admin falls through to a 404. This registers
// the same static-file + SPA-fallback behavior directly as a Hono route on
// `app`, registered after createCmsApp() so the already-registered, more
// specific /admin/api/* routes still win over this /admin/* wildcard.
export function adminStaticRoute(adminPrefix: string): string {
  return `
import { resolve, extname } from 'node:path'
import { readFile, stat } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { resolveStaticFile, ADMIN_MIME } from '@bobbykim/manguito-cms-api/runtime'

const __dist = fileURLToPath(new URL('.', import.meta.url))
const adminDir = resolve(__dist, 'admin')
const ADMIN_PREFIX = ${JSON.stringify(adminPrefix)}

app.get(\`\${ADMIN_PREFIX}/*\`, async (c) => {
  const resolved = resolveStaticFile(adminDir, c.req.path.slice(ADMIN_PREFIX.length) || '/')
  let filePath = resolved ?? resolve(adminDir, 'index.html')
  try {
    const s = await stat(filePath)
    if (!s.isFile()) filePath = resolve(adminDir, 'index.html')
  } catch {
    filePath = resolve(adminDir, 'index.html')
  }
  try {
    const data = await readFile(filePath)
    // Hashed assets cache forever; the SPA shell revalidates every load so a
    // new deploy's index.html is never served stale from cache.
    const isAsset = c.req.path.startsWith(ADMIN_PREFIX + '/assets/')
    return new Response(data, {
      headers: {
        'Content-Type': ADMIN_MIME[extname(filePath).slice(1).toLowerCase()] ?? 'application/octet-stream',
        'Cache-Control': isAsset ? 'public, max-age=31536000, immutable' : 'no-cache',
      },
    })
  } catch {
    return c.text('Not found', 404)
  }
})`
}

// ─── AWS Lambda ───────────────────────────────────────────────────────────────

function lambdaEntry({ adminPrefix }: ServerEntryOptions): string {
  return `// Generated by manguito build — do not edit manually
import { handle } from 'hono/aws-lambda'
${appSetup()}
${adminStaticRoute(adminPrefix)}

export const handler = handle(app)
`
}

// ─── Vercel ───────────────────────────────────────────────────────────────────

function vercelEntry({ adminPrefix }: ServerEntryOptions): string {
  return `// Generated by manguito build — do not edit manually
import { handle } from 'hono/vercel'
${appSetup()}
${adminStaticRoute(adminPrefix)}

export default handle(app)
`
}
