import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { VersionModel } from '@bobbykim/manguito-cms-core'
import type { BakedVersionModel } from '@bobbykim/manguito-cms-api'

/**
 * Reduces the full `VersionModel` to the shape the api actually needs at
 * runtime (`CreateCmsAppOptions['versions']`).
 *
 * `union` is deliberately omitted: it IS the current registry, which is
 * baked/passed separately and which createCmsApp already receives, so
 * including it would duplicate the whole registry.
 *
 * Shared by `generateVersionModel` below (bakes it to disk for `build`) and
 * `manguito dev`'s two `createCmsApp` call sites (passes it in-memory) — one
 * reduction, three consumers.
 */
export function reduceVersionModel(model: VersionModel): BakedVersionModel {
  return { current: model.current, live: model.live, projections: model.projections }
}

/**
 * Writes .manguito/version-model.ts.
 *
 * The api has no filesystem access to the schema at runtime — in Lambda the
 * schemas/ tree is not deployed — so the model is computed here and baked,
 * exactly as the registry is.
 */
export async function generateVersionModel(model: VersionModel, targetDir: string): Promise<void> {
  const reduced = reduceVersionModel(model)
  const content = [
    '// GENERATED by manguito build — do not edit.',
    "import type { BakedVersionModel } from '@bobbykim/manguito-cms-api'",
    '',
    `export const versionModel: BakedVersionModel = ${JSON.stringify(reduced, null, 2)}`,
    '',
  ].join('\n')
  await writeFile(join(targetDir, 'version-model.ts'), content, 'utf8')
}
