import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { VersionModel } from '@bobbykim/manguito-cms-core'

/**
 * Writes .manguito/version-model.ts.
 *
 * The api has no filesystem access to the schema at runtime — in Lambda the
 * schemas/ tree is not deployed — so the model is computed here and baked,
 * exactly as the registry is.
 *
 * `union` is deliberately omitted: it IS the current registry, which is baked
 * separately and which createCmsApp already receives, so including it would
 * duplicate the whole registry in the generated bundle.
 */
export async function generateVersionModel(model: VersionModel, targetDir: string): Promise<void> {
  const reduced = { current: model.current, live: model.live, projections: model.projections }
  const content = [
    '// GENERATED by manguito build — do not edit.',
    "import type { BakedVersionModel } from '@bobbykim/manguito-cms-api'",
    '',
    `export const versionModel: BakedVersionModel = ${JSON.stringify(reduced, null, 2)}`,
    '',
  ].join('\n')
  await writeFile(join(targetDir, 'version-model.ts'), content, 'utf8')
}
