import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

type ServerEntryOptions = {
  adminPrefix: string
  apiPrefix: string
}

export async function generateServerEntries(
  options: ServerEntryOptions,
  targetDir: string,
): Promise<void> {
  await Promise.all([
    writeFile(join(targetDir, 'server.ts'), serverEntry(options), 'utf8'),
    writeFile(join(targetDir, 'handler.ts'), lambdaEntry(), 'utf8'),
    writeFile(join(targetDir, 'vercel.ts'), vercelEntry(), 'utf8'),
  ])
}

// ─── Shared preamble ──────────────────────────────────────────────────────────

function appSetup(): string {
  return `import config from '../../manguito.config.js'
import { schemaRegistry } from './schema-registry.js'
import { createCmsApp } from '@bobbykim/manguito-cms-api'
import { createPostgresAdapter } from '@bobbykim/manguito-cms-db'

const dbAdapter = createPostgresAdapter()
await dbAdapter.connect()

const { app } = createCmsApp({
  name: config.name,
  registry: schemaRegistry,
  db: dbAdapter.getDb(),
  storage: config.storage,
  prefix: config.api.prefix,
  ...(config.api.media ? { media: config.api.media } : {}),
})`
}

// ─── Node HTTP server ─────────────────────────────────────────────────────────

function serverEntry({ adminPrefix, apiPrefix }: ServerEntryOptions): string {
  return `// Generated by manguito build — do not edit manually
import { createServer } from 'node:http'
import { resolve, extname } from 'node:path'
import { readFile, stat } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
${appSetup()}

const __dist = fileURLToPath(new URL('.', import.meta.url))
const adminDir = resolve(__dist, 'admin')
const uploadsDir = resolve(__dist, '..', 'uploads')

const MIME: Record<string, string> = {
  html: 'text/html; charset=utf-8',
  js: 'application/javascript',
  mjs: 'application/javascript',
  css: 'text/css',
  json: 'application/json',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  svg: 'image/svg+xml',
  ico: 'image/x-icon',
  woff: 'font/woff',
  woff2: 'font/woff2',
  webp: 'image/webp',
}

const API_PREFIX = ${JSON.stringify(apiPrefix)}
const ADMIN_PREFIX = ${JSON.stringify(adminPrefix)}

const port = Number(process.env['PORT'] ?? 3000)

createServer(async (req, res) => {
  const url = req.url ?? '/'
  const path = url.split('?')[0] ?? '/'

  // ── API (Hono) ──────────────────────────────────────────────────────────────
  if (path.startsWith(API_PREFIX) || path.startsWith('/admin/api')) {
    const headers = new Headers()
    for (const [k, v] of Object.entries(req.headers)) {
      if (typeof v === 'string') headers.set(k, v)
      else if (Array.isArray(v)) v.forEach((vi) => headers.append(k, vi))
    }
    const body = req.method === 'GET' || req.method === 'HEAD' ? undefined : req
    const honoReq = new Request(\`http://localhost:\${port}\${url}\`, {
      method: req.method,
      headers,
      // @ts-expect-error -- Node 22 supports body as readable stream with duplex
      body,
      ...(body ? { duplex: 'half' } : {}),
    })
    const honoRes = await app.fetch(honoReq)
    res.statusCode = honoRes.status
    const setCookies: string[] = []
    honoRes.headers.forEach((v, k) => {
      if (k.toLowerCase() === 'set-cookie') setCookies.push(v)
      else res.setHeader(k, v)
    })
    if (setCookies.length > 0) res.setHeader('set-cookie', setCookies)
    res.end(Buffer.from(await honoRes.arrayBuffer()))
    return
  }

  // ── Uploads (local storage) ─────────────────────────────────────────────────
  if (path.startsWith('/uploads/')) {
    const rel = path.slice('/uploads/'.length).replace(/\\.\\./g, '')
    const filePath = resolve(uploadsDir, rel)
    if (!filePath.startsWith(uploadsDir + '/')) { res.statusCode = 403; res.end('Forbidden'); return }
    try {
      const data = await readFile(filePath)
      res.setHeader('Content-Type', MIME[extname(filePath).slice(1).toLowerCase()] ?? 'application/octet-stream')
      res.end(data)
    } catch { res.statusCode = 404; res.end('Not found') }
    return
  }

  // ── Admin SPA ────────────────────────────────────────────────────────────────
  if (path.startsWith(ADMIN_PREFIX)) {
    const rel = path.slice(ADMIN_PREFIX.length) || '/'
    const candidate = resolve(adminDir, '.' + rel)
    let filePath = candidate
    try {
      const s = await stat(candidate)
      if (!s.isFile()) filePath = resolve(adminDir, 'index.html')
    } catch {
      filePath = resolve(adminDir, 'index.html')
    }
    try {
      const data = await readFile(filePath)
      res.setHeader('Content-Type', MIME[extname(filePath).slice(1).toLowerCase()] ?? 'application/octet-stream')
      res.end(data)
    } catch { res.statusCode = 404; res.end('Not found') }
    return
  }

  res.statusCode = 404
  res.end('Not found')
}).listen(port, () => {
  console.log(\`Server listening on http://localhost:\${port}\`)
})
`
}

// ─── AWS Lambda ───────────────────────────────────────────────────────────────

function lambdaEntry(): string {
  return `// Generated by manguito build — do not edit manually
import { handle } from 'hono/aws-lambda'
${appSetup()}

export const handler = handle(app)
`
}

// ─── Vercel ───────────────────────────────────────────────────────────────────

function vercelEntry(): string {
  return `// Generated by manguito build — do not edit manually
import { handle } from 'hono/vercel'
${appSetup()}

export default handle(app)
`
}
